### ISSUE TITLE
民政部县以下数据

### ISSUE THREAD

**Issue by lmmmmmm** [tonyc726/china-administrative-division#1]
你好，请问一下有民政部到县以下的乡镇/街道数据吗？

**Comment by tonyc726** [comment]
民政部没有县以下数据的，只有统计局的是有的，最后一级是街道，数据都已经爬取了，只不过导出的文件有点大，所以没有放在仓库里面

**Comment by lmmmmmm** [comment]
好的，谢谢您了。
