### ISSUE TITLE
master分支直接下载运行报错

### ISSUE THREAD

**Issue by YazhenZhang** [tonyc726/china-administrative-division#24]
(node:13012) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'error' of null
    at F:\work\china-administrative-division\crawler\stats.gov.cn.js:771:14
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

代码位置：
  if (isArray(queues)) {
    // 初始化历史运行记录
    let runHistory = [];
    try {
      // 读取历史运行记录
      const runHistoryCache = await pageCacheDB.get('runHistory');
      runHistory = JSON.parse(runHistoryCache);
    } catch (error) {
      logger.error('历史运行记录读取失败');
      logger.error(error);
    }

**Comment by YazhenZhang** [comment]
是要加什么配置吗

**Comment by tonyc726** [comment]
@YazhenZhang 
你的nodejs环境版本是多少？建议用v12以上的版本；

然后清理本地缓存以后再用`npm ci`重新安装一下依赖项；

刚才我重新用windows 10环境和macOS 自测了一次，都没有遇到你的问题🤣

**Comment by YazhenZhang** [comment]
你好，邮件已收到！
