### ISSUE TITLE
categoryCode

### ISSUE THREAD

**Issue by HappyManYun** [tonyc726/china-administrative-division#3]
{
                    "name": "棉一居委会",
                    "code": "130102001001",
                    "categoryCode": "111"
                  } 

中的categoryCode是代表什么

**Comment by tonyc726** [comment]
城乡分类代码

**Comment by HappyManYun** [comment]
我看有个属性代码，可以算出这个，但是不知道怎么算的所以问下

**Comment by tonyc726** [comment]
城乡分类代码是国家统计局制定的，你可以看一下[民政统计代码编制规则](https://github.com/tonyc726/china-administrative-division/blob/master/docs/%E6%B0%91%E6%94%BF%E7%BB%9F%E8%AE%A1%E4%BB%A3%E7%A0%81%E7%BC%96%E5%88%B6%E8%A7%84%E5%88%99.md)
